### ISSUE TITLE
Provide a TODO list

### ISSUE THREAD

**Issue by revl-ca** [gvanderest/undermountain#1]
If possible to provide a todo list with what is in progress and what is the suggested order of features that needs to be implemented to make it playable.

S.

**Comment by gvanderest** [comment]
Hey there.

Let me begin by apologizing for not having seen this issue at all until about half an hour ago.  I've compiled a `TODO.md` list to give you a sense of the things I've been thinking about incorporating into the engine.  

I could probably further group it under what I'm working on next versus what I'd consider a useful/playable state, versus long term goals.
